setup.cfg
Current `setup.cfg` results in an error when I run `pip install -e .`. The error ends with:
`[...] 
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'=1.1.1'": Expected stringEnd`
I think there is a missing `=`, as per `pip`'s convention. 
If other users are encountering this problem, this PR should fix it.
=> Fixes setup config error

smartsim/entity/model.py, smartsim/experiment.py
There were two locations where the `run_settings` parameter for `Experiment.create_model` and  `Model.__init__` was documented as being of type dictionary when it should have been documented as having the type RunSettings. This was due to the documentation not being entirely updated when the concept of RunSettings was introduced in the 0.3.0 release.
=> Fix to documentation

requirements-dev.txt, requirements.txt, setup.cfg, smartsim/database/orchestrator.py
Remove usage of redis-py-cluster
The orchestrator utilized a third-party library called redis-py-cluster to check the cluster status after initialization
this has been replaced with SmartRedis such that the check_cluster_status function now utilizes the SmartRedis client
=> Remove usage of redis-py-cluster

Makefile, tests/test_dbnode.py
Small edits to tests introduced in PR #53 that left some testing files around.
Also introduces a new testing flag in the makefile for users who want to run the test suite on interactive allocations without the ``full_wlm`` tests which assume full control over the host machine.
=> Edit Makefile and test fix

.github/workflows/run_local_tests.yml, Makefile, conftest.py, smartsim/database/orchestrator.py, tests/test_configs/smartredis/consumer.py, tests/test_configs/smartredis/producer.py, tests/test_ensemble.py, tests/test_orchestrator.py, tests/with_smartredis/test_smartredis.py
There were two problems with the ``get_address`` and ``is_active`` implmentations
1. itertools was not imported
2. ports are integers and hence cause the string formation to fail.
New tests were added that increase ``Orchestrator`` coverage to 99%. 
This was my fault for not catching this in review.
=> Fix orchestrator bugs introduced in 98341ca

smartsim/entity/dbnode.py
When we parse RedisIP info, we always sleep 5 seconds, even if we found the host. This means that if we have N nodes, we wait for N*5 seconds, but most likely, all nodes will have written their info when we parse it for one. This quick fix removes the sleep operation when we find host (but leaves it otherwise).
=> Add condition to redis IP sleep

conftest.py, doc/installation.rst, doc/orchestrator.rst, modules/FindTensorFlow.cmake, smartsim/bin/scripts/build-redisai-cpu.sh, smartsim/bin/scripts/build-redisai-gpu.sh, smartsim/database/redis6.conf, smartsim/launcher/lsf/lsfLauncher.py, tutorials/cheyenne/launch_database_cluster.py, tutorials/summit/README.md, tutorials/summit/hello.c, tutorials/summit/launch_database_cluster.py, tutorials/summit/launch_distributed_model_lsf.py, tutorials/summit/launch_distributed_model_ompi.py, tutorials/summit/run.sh
This PR patches a problem RedisAI has to find pre-installed TF. 
We store a modified version of RAI's `FindTensorFlow.cmake` file, where we add TF 2.4 (which covers all patch releases) to the accepted TF versions. Moreover, we change the library name (the shared object file has changed). 
Notice this was solely tested on Summit (and it's our current solution on that system).
=> Add new FindTensorFlow.cmake

conftest.py, tests/on_wlm/test_base_settings_on_wlm.py
This PR actually just adds the tests for LSF base settings, as they were already supported in the LSF launcher. Therefore, the status is now:
- in the LSF launcher, `RunSettings` objects are supported
- in `conftest.py`, `get_base_run_settings` can generate `RunSettings` for LSF.
Let me know if there was something else to be added!
=> Add base run settings to tests for LSF

smartsim/entity/ensemble.py, smartsim/entity/model.py, smartsim/generation/modelwriter.py, smartsim/utils/helpers.py, tests/backends/run_sklearn_onnx.py, tests/backends/run_tf.py, tests/backends/run_torch.py, tests/test_configs/multi_tags_template.sh, tests/test_configs/smartredis/consumer.py, tests/test_configs/smartredis/producer.py, tests/test_ensemble.py, tests/test_generator.py, tests/test_smartredis.py
This PR enhances the current way parameters and models are generated in two ways:
- add the possibility of specifying `arg_params` in `Ensemble`s: `arg_params` are treated like `params` but set as `exe_args` in the created `Model`s -- thus they are set even without the generation step.
- allow multiple tagged parameters on same line
This PR resolves #16 #40
=> Improve parameter handling with and without generation

smartsim/experiment.py, smartsim/settings/base.py, smartsim/settings/cobaltSettings.py, smartsim/settings/lsfSettings.py, smartsim/settings/settings.py, smartsim/settings/slurmSettings.py, tests/full_wlm/test_generic_batch_launch.py, tests/test_batch_settings.py, tests/test_configs/cov/local_cov.cfg
create_batch_settings is a portability improvement for users writing driver scripts.
With this function, a user no longer needs to specify a batch settings class, the function will initialize a given class based on the launcher
=> Experiment.create_batch_settings

smartsim/launcher/pbs/pbsParser.py, smartsim/settings/base.py, smartsim/settings/cobaltSettings.py, smartsim/settings/lsfSettings.py, smartsim/settings/pbsSettings.py, smartsim/settings/settings.py, smartsim/settings/slurmSettings.py, tests/backends/test_tf.py, tests/backends/test_torch.py, tests/full_wlm/test_generic_batch_launch.py, tests/on_wlm/test_launch_orc_slurm.py, tests/on_wlm/test_simple_base_settings_on_wlm.py
One function `set_hostlist` needs to `pass`, as this is only available (and already present) at batch level. The other two missing functions map the concept of node to that of RS, as it is the closest entity in LSF.
=> Add missing functions to LSFSettings API

requirements-dev.txt, requirements.txt, setup.py, smartsim/_core/launcher/step/step.py, smartsim/_core/utils/helpers.py
This PR removes the numpy dependency from SmartSim since SmartRedis already has numpy as a dependency. `step.py` needed to be altered such that it does not use numpy to generate a unique string. numpy was also removed from `requirements.txt`, `requirements-dev.txt`, and `setup.py`.
=> Remove numpy

smartsim/database/orchestrator.py, tests/on_wlm/test_launch_orc_cobalt.py, tests/on_wlm/test_launch_orc_pbs.py, tests/on_wlm/test_launch_orc_slurm.py
Orchestrator method is_active() had the incorrect set of parameters for check_cluster_status() call.  This PR fixes that and adds a check in WLM tests to check that get_address() (which calls this method) returns correctly sized result.
=> Fix is_active() call to check_cluster_status()

Makefile, doc/api/smartsim_api.rst, doc/conf.py, doc/tutorials/05_training.rst, tests/backends/test_dataloader.py, tutorials/01_getting_started/01_getting_started.ipynb, tutorials/05_ml_training/train_tf.ipynb, tutorials/05_ml_training/train_torch.ipynb
This PR adds fixes for some issues introduced by the DataLoaders, namely:
- DataLoaders were incorrectly linked in docs
- DataLoader notebooks included kernels and that made `make docks` fail
- `test_dataloaders.py` used the standard Redis port for the orchestrators, but that port is already in use on some systems (switched to 6780)
=> DataLoader fix

.docs_static/CNAME, .docs_static/index.html, .github/workflows/build_docs.yml, Makefile
Fix `build_docs` github action that was previously broken. Some other minor improvements were added as part of this fix.
Changes include:
- `build_docs` action is triggered when we push to develop branch
- Previously, it was on PR closed, which isn't necessarily a merge, i.e. a contributor could close a PR without merging and the action would still trigger
- Use `GITHUB_TOKEN` instead of personal authentication (PA) credentials to push
- Use "action@github.com" as the git author (user) to distinguish automated commits from human commits
- Check static files from doc branch into develop, so that we can modify
them in a regular PR to `develop`, rather than have to edit the doc branch
directly. I'd like for us to get to a point where doc branch pushes are fully automated, so we should never …
=> Fix build_docs github action + some minor improvements

doc/changelog.rst, doc/developer.rst, doc/experiment.rst, doc/launchers.rst, doc/orchestrator.rst
High Level Docs Update:
- Pass over `experiment`/`launchers`/`orchestrator` docs for spelling/grammar/wording
- Add brief description of overall goals for release
- Compiles a list of PRs made since the last release into a single list
- Similar PRs grouped together into an overall heading
- Provides a brief description of the changes made in each
- Willing to have this be pruned and/or sorted in nicer categories based on maintainers suggestions
=> High Level Docs Update / Changelog for 0.4.0

.github/workflows/run_tests.yml
Run github action test suite in pull requests only, instead of on any push to any branch on any fork.
Note that the `pull request` trigger includes open, reopen, and sync, where sync includes pushing commits to a branch with an open PR.
=> Run github action test suite in PRs only

doc/requirements-doc.txt, docker/docs/dev/Dockerfile
Moved the additional python package dependencies from the docker file to the documentation requirements file.
This resolves a `make docks` bug that showed up on MacOS with python 3.8+ where the dependency resolution resulted in an error (specifically, when trying to resolve version for `appnope`).
Also removed `ipykernel` and `ipython` from requirements, since they are included as dependencies to `nbsphinx`.
=> Move docker pip install to requirements-doc.txt

.github/workflows/release.yml, doc/installation.rst, pyproject.toml, setup.cfg
The SmartSim documentation lists CMake version 3.10 as a requirement for SmartSim and SmartRedis.  SmartRedis was upgraded to a minimum CMake version of 3.13.  This PR updates the documentation.  Also, to maintain a consistent build and test environment, the CMake minimum version has also been upgrade in SmartSim.   The current version of CMake is 3.23, so users are unlikely to notice a change unless they are using a very old version of CMake, and newer versions of CMake are easily installed in a conda environment.
=> Update CMake version from 3.10 to 3.13

doc/requirements-doc.txt
One liner, forgot to add ipython back into the build. it's needed separately from nbsphinx as detail in this issue
https://github.com/spatialaudio/nbsphinx/issues/24
=> Add ipython dep to doc build

smartsim/_core/_cli/build.py, smartsim/_core/_install/builder.py
RedisAI TF backend requires libtensorflow. The standard RedisAI build script calls `get_deps.sh`, which downloads the appropriate libtensorflow tarball from Google's repository. 
In this PR, we address the situation in which the tarball is not available (e.g. if it is missing for a given architecture), but the user has libtensorflow installed on the system. Notice that until RAI 1.2.3, it was possible to use a `FindTensorflow.cmake` module to use the system-installed tensorflow.
We add the option `--libtensorflow_dir` to `smart build`, and symlink the user-provided libtensorflow dirs into RAI's dependency tree.
Another build issue, raised in #153, i.e. the handling of uppercase device specification (such as `--device CPU`) was fixed in this PR.
=> Add option to use system-available libtensorflow for RedisAI

conftest.py, doc/installation.rst, smartsim/database/orchestrator.py
This is a hotfix PR, a mishandled option is preventing LSF orchestrators from using more than one GPU per shard.
=> Fix wrong handling of LSF gpus_per_shard option

smartsim/database/orchestrator.py
This PR fixes an incorrect usage of `kwargs` in `Orchestrator._build_run_settings`.
Since `run_args` is not popped from `kwargs`, when we use it as argument in `create_run_settings`, two copies are passed, causing an error.
We also eliminated an unused Slurm option setting, which was redundant.
=> Fix run_args issue in create_database

conftest.py
This PR fixes an issue encountered when SmartSim is installed under a path which contains a `.`
=> Fix problem with dot in path

smartsim/_core/_cli/build.py
This PR fixes #162. 
There are four cases that this PR accounts for which have been confirmed to work on local machine and Horizon.
1. User attempts to run `smart build` when `RAI_PATH` is set and backends are installed
- Inform user that backends are already built, tell them where they are built, and notify the user that there is no reason to build.
2. User attempts to run `smart build` when `RAI_PATH` is set, but backends are not installed
- Inform user that before running `smart build`, they should unset `RAI_PATH`
3. User attempts to run `smart build` when `RAI_PATH` is not set and backends are installed
- Inform user that they need to run `smart clean` before running `smart build`
4. User attempts to run `smart build` when `RAI_PATH` is not set and backends are not installed
- Allow …
=> Fix re-run smart build bug

doc/contributing_examples.rst, doc/index.rst, doc/requirements-doc.txt
This PR adds a section about the SmartSim Zoo to the documentation. A page about the Zoo has been added in the "Getting Started" section.
=> Add SmartSim Zoo Info to Docs

smartsim/_core/generation/modelwriter.py
Prevent the model writer from hanging if a tag is not matched. Also, add code to allow an unmatched tag to be treated as a fatal error instead of just a warning
=> Don't hang on missing tag value

doc/conf.py
This PR adds a GitHub button to the documentation. The button provides an easy way for viewers of the documentation to jump straight to the source code, and also to jump straight to creating an issue in the SmartSim repo.
=> Add GitHub button to docs

smartsim/_core/launcher/step/slurmStep.py, smartsim/settings/base.py, smartsim/settings/mpirunSettings.py, smartsim/settings/slurmSettings.py, tests/test_openmpi_settings.py
Remove preset environment variables from slurmSettings and mpirunSettings since they are no longer needed.
Some other clean-ups:
- Check env var value types earlier in the process to ensure types are correct before launching any jobs
- Added a note to the `update_env` docs to inform users on how to have smartsim inherit the user environment
- Only throw `--export` flag if env_vars is not empty, otherwise we get an argument parsing error
Verified full testing passes on an HPC system with `SMARTSIM_TEST_LAUNCHER=slurm`.
Resolves #128
=> Remove preset environment variables from slurmSettings and mpirunSettings

.gitignore, setup.py, smartsim/_core/_cli/build.py, smartsim/_core/_cli/clean.py, smartsim/_core/_cli/cli.py, smartsim/_core/_install/buildenv.py, smartsim/_core/_install/builder.py, smartsim/_core/config/config.py, smartsim/_core/launcher/colocated.py, smartsim/_core/utils/redis.py, smartsim/database/orchestrator.py, tests/test_config.py
This PR adds the ability to use `KeyDB` in place of `Redis` as the database through a new `--keydb` flag for `smart build`. This flexibility enables users to maximize their throughput if they desire.
=> Keydb support

docker/dev/Dockerfile, docker/prod/Dockerfile
This PR adds TF to the backend which are built in the tutorial containers (prod, dev).
The tutorials-dev container worked fine on my workstation, completing the whole tutorial in  less than 5 minutes.
=> New docker container for tutorials

smartsim/_core/_install/builder.py
Currently ``database_name`` is set to ``KeyDB``, but when the command ``smart build --keydb`` is executed the following error is encountered:
```bash
[SmartSim] ERROR [Errno 2] No such file or directory: 'SmartSim/smartsim/_core/.third-party/keydb'
```
This PR changes the ``database_name`` to ``keydb``.
=> Fix keydb directory name during build

smartsim/settings/mpirunSettings.py
Updates the  `MpiexecSettings` (and all other OpenMPI settings classes) to use `subprocess.run` as opposed to `subprocess.check_output` when checking version statements so that it can handle a non-zero status return code.
=> Mpiexec Patch

smartsim/settings/base.py
Stumbled into a typo in RunSettings. Quick fix implemented:
- Fix typo in `RunSettings.update_env`: `val_types_union` -> `val_types`
- black
=> RunSettings Typo

requirements-dev.txt, setup.py
Added version of Click in set-up.py
Now when users install SmartSim in a new virtual environment and run `pip install -e .\[ml,dev\] `, then `make style`, the updated version of Click will now work with the existing version of Black
`make style` will pass
=> Updated version of Black

requirements.txt, setup.py, tests/full_wlm/test_wlm_helper_functions.py
This PR mitigates issues when a Slurm or PBS system is set up so that not all environment variables are populated. 
If the `alloc_specs` fixture is not defined (see commit 4bd5e23), the functions using it won't be testsd.
=> Avoid checking for alloc_specs if it is not defined

doc/api/smartsim_api.rst, smartsim/settings/containers.py
Add Singularity docs to SmartSim API docs.
I was on the fence about exposing the base class, `Container`. It has no use for a user, but it is the  type referenced in arguments, e.g. 
```python
def create_run_settings(self, ..., container: Container, ...):
...
```
I opted for leaving `Container` docs out in this PR, but am open to changing that if the reviewer disagrees. This decision can also be revisited in the future, if users are finding the current form confusing.
=> Singularity API documentations

tests/backends/test_dbmodel.py
Currently, running tests when TensorFlow is not installed will result in a failed test. This should not happen. This PR fixes it.
=> Skip DBModel test file when TF not available

tests/backends/run_sklearn_onnx.py
This PR aims at fixing the ONNX test, which has been erratically failing in CI/CD pipelines. 
I identified one possible source of errors in the fact that we overwrite the ONNX model several times, and - possibly - the model stored in the DB is not updated correctly (thus resulting in the error `Number of keys given as OUTPUTS here does not match model definition`). This hints at a bug in one of the used libraries (possibly RedisAI), thus we can not fix it completely: we can just avoid triggering it, by not overwriting models.
I also updated one function to use list of strings for inputs, instead of just a string (which is anyhow accepted by SmartRedis).
While I can not be sure that this fixes the problem, I have run the test 80 times in a row and it never failed.
=> Fix ONNX test

doc/installation.rst
https://github.com/CrayLabs/SmartRedis/pull/277 removes the `from_source.rst`
file because it was largely redundant. This small PR updates references to that
file with `lib.rst`
=> Update installation doc after SmartRedis documentation update

.github/workflows/run_tests.yml, smartsim/_core/control/controller.py, smartsim/_core/entrypoints/colocated.py, smartsim/_core/launcher/colocated.py, smartsim/entity/model.py, tests/backends/test_dbmodel.py, tests/on_wlm/test_colocated_model.py, tests/test_colo_model_local.py
`Models` can now connect to a co-located database using a
Unix Domain Socket (UDS). In synthetic benchmarks, this can
lead to significant improvements over using the loopback
interface over TCP/IP. To ensure compatibility with previous
scripts we now provide the following interfaces:
- `colocate_db` (original): Will throw a `DeprecationWarning`
but otherwise just wraps `colocate_db_tcp`
- `colocate_db_tcp`: Listens for connections over the loopback
- `colocate_db_uds`: Listens for connections over UDS
=> Domain Socket Support for co-located databases

setup.py, smartsim/_core/_install/buildenv.py
Address bad `setup.py` syntax no longer accepted by `setuptools>=67.0.0`
=> Fix Setup Script Syntax

smartsim/_core/_cli/build.py, smartsim/_core/_cli/cli.py, smartsim/_core/entrypoints/colocated.py
Removes use of `exit` and replaces with `sys.exit` to handle the unlikely case where users (foolishly) try to use the `smart` cli without fully initializing `site` module
=> Better Exit Usage

tests/test_run_settings.py
Adds new test for testing mpiexec settings that is able to handle slurm's `mpiexec.slurm` wrapper.
=> Fix Mpiexec Test on Slurm Based Machines

smartsim/entity/model.py
When trying to run a model colo on lsf, a key error will be raised when setting the number of db cpus
=> fix key error for colo lsf

smartsim/entity/model.py, smartsim/settings/lsfSettings.py
An object of type `dict[str, Any] | None` is never equivalent to `True`. This needs to be cast to a bool or make a container-is-not-empty check. This PR does the later.
=> Fix Unreachable Block on Colo Lsf Settings

smartsim/experiment.py
The current `summary` function lets `tabulate` auto-format numbers (even when they are strings). On Slurm, task ids take the form `<job_id>.<task_id>` and `tabulate` will interpret them as floating point numbers, displaying them incorrectly. 
For example:
```bash
|    | Name           | Entity-Type   |       JobID |   RunID |    Time | Status    |   Returncode |
|----|----------------|---------------|-------------|---------|---------|-----------|--------------|
|  0 | producer_0     | Model         | 3.50355e+06 |       0 | 16.7805 | Completed |            0 |
|  1 | producer_1     | Model         | 3.50355e+06 |       0 | 13.5526 | Completed |            0 |
|  2 | orchestrator_0 | DBNode        | 3.50355e+06 |       0 | 41.6172 | Cancelled |            0 |
```
this PR disable …
=> Fix job id format, enforce time format

smartsim/_core/launcher/step/slurmStep.py, smartsim/settings/slurmSettings.py, tests/test_batch_settings.py, tests/test_run_settings.py, tests/test_slurm_settings.py
This PR fixes two defects related to passing environment variables to slurm jobs.
1. CSV-valued environment variables are not passed to MPMD executions
2. CSV-valued environment variables are passed twice
For (1), add populating source env with `env k1=v1,v2 {srun} --export k1`
For (2), perform key-only export of csv-valued vars:
- old: `env k1=v1,v2 srun --export k1=v1,v2`
- new: `env k1=v1,v2 srun --export k1`
Sample demonstrating "double export" overwrite & solution in non-mpmd:
```
mcb@h:~> env abc=123,456 def=234,345 srun --output /home/users/mcbridch/outsolo.txt --export=abc=123,456 /usr/bin/printenv
mcb@h:~> cat ./outsolo.txt | grep abc                                                                                    
abc=123
mcb@h:~> env abc=123,456 def=234,345 srun --output …
```
=> exclude csv-valued env values from --export, enable csv-valued in mpmd

codecov.yml
The updated codecov integration will occasionally flag PRs as failing due to decreases in code coverage. Investigating the logs points to this being sporadic changes due to occasional failures when uploading code coverage. To avoid false positives and a stopgap solution, the threshold for code coverage is set to 0.5% instead of the default 0%
=> Relax codecov threshold

smartsim/experiment.py
The factory method `Experiment.create_run_setttings` lists the `run_args` param to be a `list[str]`, but every RS constructor expects a `dict[str, str]` without any casting being done behind the scenes.
=> Fix Type Hint in Doc for `create_run_settings`

doc/changelog.rst, doc/orchestrator.rst, smartsim/_core/config/config.py, smartsim/_core/control/manifest.py, smartsim/_core/entrypoints/colocated.py, smartsim/_core/entrypoints/redis.py, smartsim/_core/launcher/colocated.py, smartsim/database/orchestrator.py, tests/backends/test_dataloader.py, tests/backends/test_dbmodel.py, tests/on_wlm/test_containers_wlm.py, tests/on_wlm/test_generic_orc_launch.py, tests/on_wlm/test_wlm_orc_config_settings.py, tests/test_orchestrator.py
This PR adds the possibility of binding `Orchestrator`s and co-located DBs to multiple network interfaces. It also adds the `--bind-source-addr` argument to any Redis DB we deploy, making sure shards bind to an address we know _a priori_.
=> Multiple network interface binding

.github/workflows/release.yml, .github/workflows/run_tests.yml, doc/changelog.rst
We had pinned the MacOS X runner image to 10.15. This particular image on Github Actions began deprecation in May 2022. The runner itself is now no longer available and so all MacOS X Github actions are timing. This bumps the version to the latest image macos-12
=> Bump the MacOSX runner image version

doc/changelog.rst, doc/sr_fortran_walkthrough.rst, doc/sr_integration.rst
The examples in the Fortran documentation examples used a mixture of subroutines and functions. The former was deprecated when error handling was implemented to allow the clients to bubble up a return code that Fortran applications can check. This has now been updated to allow others to use the documents as an accurate jumping off point.
Closes https://github.com/CrayLabs/SmartRedis/issues/335
=> Updates Fortran documentation for error codes

smartsim/entity/model.py
This is a small clarification of the doc strings for ``attach_generator_files`` that clearly states multiple calls will overwrite files.
=> Clarify attach_generator_files() doc strings

doc/changelog.rst, requirements.txt, setup.py
The ``coloredlogs`` dependency version has been relaxed to prevent environment conflicts.  No errors were seen in log outputs.  The dependency was updated in both ``requirements.txt`` and ``setup.py`` until a later issue removes redundant dependencies.
=> Update coloredlogs version

doc/changelog.rst, smartsim/experiment.py
Currently there is a 10 second pause if ``summary=true`` is provided to ``Experiment.start()``.  After receiving user feedback, we have decided to remove that pause (#294).  A separate issue has been posted to enable a preview of the experiment launch summary without invoking ``Experiment.start()``.
=> Remove wait associated with Experiment start summary

doc/changelog.rst, smartsim/entity/strategies.py
Small refactor of `random_permutations` to simplify code.
Notes: 
- Given that`list(product(*param_values))` was called prior to the sampling code, I assume that the permutation count is manageable.
- Since the original code used a set to identify already retrieved permutations, random.sample (sample without replacement) should work identically
=> refactor random_permutations for simplicity

.gitignore, doc/changelog.rst, smartsim/experiment.py, smartsim/settings/alpsSettings.py, smartsim/settings/base.py, smartsim/settings/cobaltSettings.py, smartsim/settings/lsfSettings.py, smartsim/settings/mpiSettings.py, smartsim/settings/palsSettings.py, smartsim/settings/pbsSettings.py, smartsim/settings/settings.py, smartsim/settings/slurmSettings.py, tests/test_batch_settings.py, tests/test_lsf_settings.py, tests/test_model.py, tests/test_run_settings.py, tests/test_slurm_settings.py
Add a deep copy to the batch & run settings `__init__` methods. This ensures that changes to collections after pass-by-ref are not unexpectedly modified after creating run/batch settings instances.
=> create_run_args copy-by-ref fix

.github/workflows/run_tests.yml, conftest.py, doc/api/smartsim_api.rst, doc/changelog.rst, doc/testing.rst, smartsim/_core/config/config.py, smartsim/_core/entrypoints/colocated.py, smartsim/entity/model.py, tests/backends/test_dbmodel.py, tests/backends/test_dbscript.py, tests/backends/test_tf.py, tests/test_configs/run_dbscript_smartredis.py
This PR addresses incorrect or inconsistent behavior in the ``Model.add_ml_model()``, ``Model.add_script()`` and ``Model.add_function()`` API.  The following changes are included in this PR:
- Update documentation to be more accurate
- Correct the code for setting models on multiple GPUs
- Update tests so that they run on GPU and multiple GPUs
- Change the default network interface for test to be ``lo`` instead of ``ipogif0``
=> Update add_ml_model and add_script

conftest.py, doc/changelog.rst, doc/orchestrator.rst, smartsim/_core/entrypoints/colocated.py, smartsim/_core/launcher/colocated.py, smartsim/_core/launcher/step/slurmStep.py, smartsim/_core/launcher/step/step.py, smartsim/entity/model.py, tests/backends/test_dbmodel.py, tests/backends/test_dbscript.py, tests/conftest/setup_test_colo/colocated_model.out, tests/on_wlm/test_colocated_model.py, tests/test_colo_model_local.py
This updates the strategy for adding a co-located deployment for simulation and database. Prior, the co-located database was always pinned to the last N logical processors on a machine. In the case of a Slurm machine, user-specified bind settings were being overwritten leading to a general inflexibility for users trying to maximize performance. Additionally, `limit_app_cpus` was not working as intended because only the launcher command was being pinned and not the application launched by the launcher command.
The changes here provide two options, `limit_db_cpus` and `db_cpu_list` to control the pinning of the co-located database. `limit_db_cpus` enables the pinning using `taskset` and `db_cpu_list` is a user-provided string that specifies which processors the orchestrator should be bound …
=> Allow pinning of the co-located database

doc/changelog.rst, tests/backends/test_dbmodel.py, tests/backends/test_dbscript.py
In PR 304 (https://github.com/CrayLabs/SmartSim/pull/304), the DB model and script tests were updated to enable testing on workload managers.  However, these tests were not constrained to run on only one node and one process during the update.  As a result, each SmartSim ``model`` and ``Ensemble`` member is run with a generic run command (e.g. ``srun``) that results in multiple, identical clones of the test entity running on each compute node (e.g. in a generic slurm interactive allocation with three nodes, a ``srun`` command without ``-N`` and/or ``-n`` arguments will launch the test script on three compute nodes).  This oversight causes a combination of key collisions that results in sporadic test failures.  This PR addresses those test failures.
=> Fix the dbmodel and dbscript test errors

.github/workflows/build_docs.yml, tests/on_wlm/test_colocated_model.py
This test is running a colo database on 4 cpus but pins the process to the range of the first 5 cpus. This seems an odd choice as there is theoretically no benefit to `taskset`ing to more than 4 cpus. This was causing also test to fail as the `custom_pinning` key  in the run settings colocated db settings is was being compared to a str of `0,1,2,3` (i.e. the firsts 4 cpus).
Given this, it seems likely that the original author intended to set the `taskset` cpu range be the first 4 cpus. This PR changes the custom task set range provided in the test from `range(5) == '0,1,2,3,4'` to `range(4) == '0,1,2,3'`
=> Set Test Colo DB Pinning to the Intended Range

tests/backends/test_dbmodel.py, tests/backends/test_dbscript.py, tests/on_wlm/test_generic_orc_launch.py
Tests were failing on swan:
- One test had hardcoded in slurm semantics
- Ensemble tests in dbmodel and dbscript were both failing because it seems like each ensemble member was potentially executing the wrong .colocated_launcher.sh script. To solve this problem for now, we add a generate step before the launch of the ensemble which puts everything into its own run directory and avoids the problem
=> Fix tests for PBS on swan

smartsim/_core/_install/buildenv.py
SmartSim can now require SmartRedis v0.4.1 which has been released on PyPI.
This updates the Version class to reflect this new release.
=> Bump the SmartRedis version to 0.4.1

doc/api/smartsim_api.rst, doc/changelog.rst, doc/developer.rst, doc/installation_instructions/platform.rst, doc/installation_instructions/platform/frontier.rst, doc/testing.rst
Fixes some warnings that arose due to incorrectly formatted documentation. Also adds, a guide for Frontier users on how to build SmartSim.
=> Make file tweaks to documentation and add Frontier guide

doc/installation_instructions/platform/frontier.rst
One missing space eliminated a code block within the Frontier documentation.
=> Fix Frontier code block in doc

smartsim/_core/_cli/utils.py
Remove explicit use of shell=True to avoid potential security issues
=> Avoid using `shell=True` 

doc/changelog.rst, smartsim/_core/entrypoints/colocated.py, smartsim/_core/launcher/step/alpsStep.py
A bug was introduced during pylint mitigation. The following error occurs when logging details of a freshly started colocated database:
```
--- Logging error ---
Traceback (most recent call last):
File "/Users/ankona/.pyenv/versions/3.9.15/lib/python3.9/logging/__init__.py", line 1083, in emit
msg = self.format(record)
File "/Users/ankona/.pyenv/versions/3.9.15/lib/python3.9/logging/__init__.py", line 927, in format
return fmt.format(record)
File "/Users/ankona/.pyenv/versions/3.9.15/lib/python3.9/logging/__init__.py", line 663, in format
record.message = record.getMessage()
File "/Users/ankona/.pyenv/versions/3.9.15/lib/python3.9/logging/__init__.py", line 367, in getMessage
msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
File …
```
=> fix for incorrect logging message format/args

smartsim/_core/launcher/cobalt/cobaltLauncher.py, smartsim/_core/launcher/local/local.py, smartsim/_core/launcher/lsf/lsfLauncher.py, smartsim/_core/launcher/pbs/pbsLauncher.py, smartsim/_core/launcher/slurm/slurmLauncher.py, smartsim/_core/launcher/taskManager.py, tests/on_wlm/test_local_step.py, tests/test_configs/check_env.py
This ticket ensures that an experiment with a workload manager will pass environment variables to unmanaged steps. This edge case occurs if a developer manually creates and attach a `RunSettings` instance instead of using the `experiment.create_run_settings` factory method.
Changes include: 
- minor formatting (multi-line statements converted to single line)
- `LocalStep` environment is passed to task manager when task is unmanaged by launcher
- slurm-specific tests added to verify task run in popen inherits calling env
=> Alter launchers to pass env when starting a local step

smartsim/_core/control/controller.py
Fix another buggy format string in logging introduced during lint mitigation.
=> Fix bug in logging msg format string

doc/changelog.rst, smartsim/_core/launcher/slurm/slurmLauncher.py
After experiencing a crash in the slurm database, tests began failing unexpectedly. This fix ensures that a warning will be logged if the database goes down again.
=> Log sacct failures

conftest.py, tests/test_config.py
Additional tests for interactions between `RAI_PATH` environment variable and default `lib_path` value when using configuration for RedisAI module.
=> Add more tests for RAI_PATH and lib path interactions

pyproject.toml, smartsim/_core/_install/buildenv.py, smartsim/_core/control/controller.py, smartsim/_core/entrypoints/colocated.py, smartsim/_core/launcher/pbs/pbsParser.py, smartsim/_core/launcher/taskManager.py, smartsim/_core/utils/helpers.py, smartsim/_core/utils/redis.py, smartsim/database/orchestrator.py, smartsim/ml/data.py, smartsim/ml/tf/data.py, smartsim/settings/settings.py
Enable `disallow_any_generics` and `warn_return_any` in pyproject.toml and mitigate issues that were identified.
=> Enable mypy generic-related checks

conftest.py, doc/changelog.rst, smartsim/entity/model.py, tests/test_colo_model_lsf.py
A model fails to properly configure colocated db settings when the run settings are of type `JsrunSettings.` This bug was introduced when protected members were made public (due to linter noting public use) but the change was partially rolled back.
The model method `_set_colocated_db_settings` attempts the following:
```
if hasattr(self.run_settings, "prep_colocated_db"):
self.run_settings.prep_colocated_db(common_options["cpus"])
```
There are no run settings classes with an attribute of that name. `JsrunSettings` does have `_prep_colocated_db` (note protected/underscore). 
```
def _prep_colocated_db(self, db_cpus: int) -> None:
cpus_per_flag_set = False
for cpu_per_rs_flag in ["cpu_per_rs", "c"]:
if run_arg_value := self.run_args.get(cpu_per_rs_flag, 0):
cpus_per_flag_set = True
...
``` …
=> Fix colocated db preparation bug when using `JsrunSettings`

smartsim/_core/control/controller.py, smartsim/_core/control/manifest.py, smartsim/_core/generation/generator.py, smartsim/_core/launcher/step/cobaltStep.py, smartsim/_core/launcher/step/pbsStep.py, smartsim/_core/launcher/step/slurmStep.py, smartsim/entity/ensemble.py, smartsim/entity/entityList.py, smartsim/entity/model.py, smartsim/settings/base.py, tests/test_batch_settings.py, tests/test_lsf_settings.py
Mitigate the following protected-access errors & remove suppression:
1. `EntityList._db_models` -> add `db_models` property returning immutable collection
2. `EntityList._db_scripts` -> add `db_scripts` property returning immutable collection
3. `Model._db_models` -> add `db_models` property returning immutable collection
4. `Model._db_scripts` -> add `db_scripts` property returning immutable collection
5. Add `Model.add_ml_model_object` passthrough to `_append_db_model`
6. Add `EntityList.add_ml_model_object` passthrough to `_append_db_model`
7. `BatchSettings._preamble` -> add `preamble` property returning immutable collection
=> Mitigate suppressed protected-access errors from pylint

tests/backends/test_dbmodel.py, tests/backends/test_dbscript.py
This PR is a quick bugfix. In the DB Object tests (bot DB scripts and DB models), we are currently calling `exp.generate` for some ensembles, but that is not needed, as they are automatically generated in the exp path.
While this PR fixes the test output path issue, there remains an issue with the generation of ensembles: the path should be honored. I will put up a different ticket for that issue.
=> Remove ensemble generation from DB Object tests

.gitignore, conftest.py, smartsim/_core/control/controller.py, smartsim/_core/launcher/launcher.py, smartsim/database/orchestrator.py, smartsim/settings/palsSettings.py, smartsim/settings/settings.py, tests/test_configs/mpi_impl_stubs/pals/mpiexec, tests/test_experiment.py, tests/test_pals_settings.py, tests/test_run_settings.py
Registers the `PalsMpiexecSettings` class in SmartsSim's `Experiment` factory methods so that the correct `_BaseMpiSettings` class is returned depending on the launcher the user is intending to use:
```py
>>> pbs_exp = Experiment(launcher="pbs", ...)
>>> rs_1 = pbs_exp.create_run_settings(run_command="mpiexec", ...)
>>> type(rs_1)  # returns a OpenMPI compliant RunSettings
<smartsim.settings.mpiSettings.MpiexecSettings object at 0x7f9fe02eee00>
>>> pals_exp = Experiment(launcher="pals", ...)
>>> rs_2 = pals_exp.create_run_settings(run_command="mpiexec", ...)
>>> type(rs_2)  # returns a PALS compliant RunSettings
<smartsim.settings.palsSettings.PalsMpiexecSettings object at 0x7f9fdaf6f1c0>
```
=> Integrate PalsMpiexecSettings into Experiment factory methods

smartsim/_core/_cli/cli.py, smartsim/_core/_cli/info.py, tests/test_cli.py
Add a smart info target for info about current SS installation
Example Output:
```
$ smart info
Smart Python Packages:
╒════════════╤═══════════╕
│ Name       │ Version   │
╞════════════╪═══════════╡
│ SmartSim   │ 0.5.0     │
│ SmartRedis │ 0.4.1     │
╘════════════╧═══════════╛
Orchestrator Configuration:
╒═══════════╤════════════════════════════════════════════════════════════╕
│ Installed │ REDIS                                                      │
│ Location  │ /Users/mrdro/repos/ssimdev/ss/smartsim/_core/bin/redis-cli │
╘═══════════╧════════════════════════════════════════════════════════════╛
Redis AI Configuration:
╒══════════════╤═════════════════════════════════════════════════════════════╕
│ Is Installed │ Installed                                                   │
│ …
```
=> Smart Info

smartsim/_core/_cli/validate.py
Closes an unneeded `mp.Connection` causing `smart` to hang.
=> `smart validate` should not hang when error in TF process

smartsim/entity/ensemble.py, smartsim/entity/files.py, smartsim/entity/model.py, tests/test_configs/to_copy_dir/mock.txt, tests/test_configs/to_symlink_dir/mock2.txt, tests/test_generator.py
This PR adds the possibility of printing files attached to models and to ensembles.
=> Print attached files

doc/installation_instructions/site-install.rst, tutorials/ml_inference/Inference-in-SmartSim.ipynb
Remove references in the docs to the (now invalid) `--only_python_pacakges` flag of `smart build`
=> Remove references in docs to nonexistent CLI flag

smartsim/_core/_cli/build.py
In the case where a user is using python 3.10 and has requested to build with
```sh
smart build --onnx
```
there is no compliant onnx wheel for python 3.10 for the ORT backend installed by default for RAI. This was leading to a `SetupError` being raised, and eventually exposing itself to the user.
This PR will handle that raised exception and pretty print the error message within, before exiting with a non-zero exit code.
=> Pretty print error message when onnx wheel not available

.github/workflows/release.yml
Updates the version of `cibuildwheel` used in the CI to `>=2.12.3`
=> Update `cibuildwheel` version

doc/changelog.rst
Adds missing PRs to change log. Updates the change log from develop to planned release number/date
=> Update changelog for release

conftest.py, smartsim/_core/control/controller.py, smartsim/_core/utils/redis.py, smartsim/database/orchestrator.py, smartsim/experiment.py, smartsim/settings/palsSettings.py, tests/backends/test_dbmodel.py, tests/test_configs/cov/local_cov.cfg
This PR changes the way `Orchestrator`s are stopped.
Currently, the `Orchestrator` process or job is simply killed: this proved not to be a good technique with some WLMs, where the launcher and the launched process are different. In such cases, it is impossible to stop a running process and orchestrators stay up until the allocation is relinquished.
With this PR, we added the execution of an explicit `shutdown` command for each DB shard, which properly terminates the Orchestrator in all cases.
A few tweaks to the current test suite were also implemented as part of this PR, to make sure that executing them through `mpiexec` on some systems did not fail.
=> Send shutdown command to DB

.github/workflows/run_tests.yml, tests/test_orchestrator.py
When trying to debug tests on the Github CI, the output from pytest is often insufficient because some errors are written to the redirected stderr and stdout of launched applications. This PR uploads the test_output directory as an artifact of the workflow on failure.
=> Publish artifacts from test_output on CI fail

README.md
The 'Install' link in README was pointing to a since moved and renamed page on the Cray Labs docs. It has been updated to now point to the basic installation of SmartSim.
=> Fix broken 'Install' link in README

setup.py
Pylint 3.0.0 was released, but it seems to have some bugs, which are making our actions fail. We are pinning its version to `<3` and will make sure to update it as soon as it is fixed.
=> Pin pylint version

smartsim/_core/config/config.py, smartsim/_core/entrypoints/redis.py, smartsim/database/orchestrator.py, smartsim/entity/dbnode.py, tests/test_dbnode.py, tests/test_orchestrator.py, tests/test_smartredis.py
A general refactor of the `DBNode` class to:
1) Remove the duplicate methods with near identical functionality where one was intended to be called if the underlying `RunSettings` were standard and the other if they were MPMD. This removes undefined behavior when the "wrong" method was called
2) Allow MPMD `DBNode`s to map information "per shard" by scraping output files for a serializable `LaunchedShardData` class.
=> DBNode: MPMD RunSettings Unification

smartsim/_core/control/jobmanager.py, smartsim/_core/control/manifest.py
This PR fixes a bug encountered when launching more than one DB from a driver script. Addresses of running DBs could get mixed and some internal checks would incorrectly fail.
=> Fixes to multi-db introspection

setup.py
With the last update of `types-tensorflow` (2.12.0.10), some types are not defined anymore, and this causes mypy to fail.
This PR pins the version number to `2.12.0.9`, which is the last compatible with TF `2.8.x`.
=> Pin version of types-tensorflow

conftest.py, smartsim/_core/config/config.py, smartsim/_core/control/controller.py, smartsim/_core/entrypoints/telemetrymonitor.py, tests/test_configs/printing_model.py, tests/test_telemetry_monitor.py
The initial telemetry monitor merge ignored a known automatic shutdown bug. The mitigation removed automatic shutdown completely.
This change solves an automatic shutdown issue when the telemetry monitor has not yet begun to monitor a task. The prior auto-shutdown condition allowed the telemetry monitor to immediately complete. 
A cooldown/timeout period has been added to avoid immediate shutdown. The telemetry monitor can now be configured to live a specific duration and avoids shutdown prior to the writing of a runtime manifest.
=> Add cooldown period to avoid immediate termination of telemetry monitor

doc/changelog.rst, pyproject.toml
The pytest groups used to split execution of the test cases for parallelization currently result in a warning message displayed during test runs.
```
=== warnings summary ===
tests/test_cli.py:49
/lus/cls01029/mcbridch/ss/tests/test_cli.py:49: PytestUnknownMarkWarning: Unknown pytest.mark.group_a - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
pytestmark = pytest.mark.group_a
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=== 52 passed, 1 warning in 0.53s ===
```
This fix adds group registrations to `pyproject.toml` to avoid those warnings:
```
=== 52 passed in 0.48s ===
```
=> Register test groups, mitigate warning

smartsim/_core/_cli/build.py, smartsim/_core/_cli/clean.py, smartsim/_core/_cli/cli.py, smartsim/_core/_cli/dbcli.py, smartsim/_core/_cli/info.py, smartsim/_core/_cli/plugin.py, smartsim/_core/_cli/site.py, smartsim/_core/_cli/validate.py, tests/test_cli.py
Discovered a bug where using the CLI "plugin" to execute smart-dash did not return the correct help text. e.g. `smart dashboard -h` returned the default help text. This fix corrects the failure to pass arguments known by the smart CLI parser to the plugin.
After fixing the initial defect:
- A bug hiding the final output of the plugin was discovered. Moved `print(plugin_stdout)` to ensure plugin stdout was displayed
- Fixed bug where tests run in vscode test runner fail to load plugin. Mitigated with importlib
- Added test to verify passthrough output for initial fix
- Added test to verify outputs when plugin is not installed
- Revert removal of positional-only arguments
=> Fix CLI bug hiding arguments matching root parser

smartsim/_core/_cli/__main__.py, smartsim/_core/_cli/plugin.py, smartsim/error/errors.py, tests/test_cli.py
Users terminating the dashboard via ctrl-c are currently shown a stacktrace:
```
(ss39) ankona@horizon:/lus/cls01029/ankona/ss> smart dashboard           
^CTraceback (most recent call last):
File "/lus/cls01029/ankona/.pyenv/versions/ss39/bin/smart", line 8, in <module>
sys.exit(main())
File "/lus/cls01029/ankona/ss/smartsim/_core/_cli/__main__.py", line 36, in main
return smart_cli.execute(sys.argv)
File "/lus/cls01029/ankona/ss/smartsim/_core/_cli/cli.py", line 87, in execute
return menu_item.handler(args, unparsed_args)
File "/lus/cls01029/ankona/ss/smartsim/_core/_cli/plugin.py", line 25, in process_execute
stdout, _ = process.communicate()
File "/lus/cls01029/ankona/.pyenv/versions/3.9.18/lib/python3.9/subprocess.py", line 1134, in communicate
stdout, stderr = …
```
=> handle interrupt, avoid displaying stack trace

doc/conf.py, doc/orchestrator.rst, tutorials/getting_started/multi_db_example/application_script.py, tutorials/getting_started/multi_db_example/multidb_driver.py
This PR merges the SmartSim mutlidb example into the craylab docs. It is step by step instructions on how to setup multiple orchestrators, connect to the orchs using smartredis clients and send, retrieve and manipulate data using the launched dbs and the ConfigOptions object. The manipulation of tensors is done with a torch function. Lastly, the source code is provided at the end of the example.
=> SmartSim Multidb example

doc/testing.rst
Bumps the required number of nodes in the test docs from 3 to 4 as required by the tests in #381 and #426.
=> Test Docs: Update Number of Required Nodes

smartsim/_core/_cli/build.py
Torch changed something in their indexing when trying to install from their provided wheels. This updates the `pip install` command within `smart build` to ensure that the appropriate packages can be found.
=> Fix index when installing torch through smart build

.github/workflows/run_tests.yml
This PR adds concurrency groups to GitHub's CI/CD workflows, preventing multiple workflows from the same PR to be launched concurrently.
=> Add concurrency group to test workflow

doc/_static/custom_tab_style.css, doc/changelog.rst, doc/conf.py
The sphinx-tabs documentation extension uses a white background for the tabs component.  This causes readability issues with the theme that we have chosen.  This PR overrides the CSS for those components to inherit the overall theme color.
=> Override sphinx-tabs background color

smartsim/_core/_cli/validate.py, tests/test_cli.py
Quality of life `smart validate` improvements:
- Set `CUDA_VISIBLE_DEVICES` environment variable within `smart validate` prior to importing any ML deps to prevent false negatives on multi-GPU systems
- Move SmartRedis logs from standard out to dedicated log file in the validation temporary directory
- Suppress `sklearn` deprecation warning by pinning `KMeans` constructor argument
=> Quality of life `smart validate` Improvements

.github/workflows/run_tests.yml, doc/changelog.rst, doc/installation_instructions/basic.rst, setup.cfg, tests/test_logs.py
Adds Python 3.11 to the SmartSim support matrix.
---
TODO before merge:
=> Python 3.11 Support

setup.py
Relaxes the required version `typing_extensions` to prevent the following error when `pip` installing via `pip install -e /path/to/local/smarsim[dev,ml,mypy]`
```sh
(venv) [drozt@hostname ss]$ pip install -e .[dev,ml,mypy]
ERROR: Cannot install smartsim and smartsim[dev,ml,mypy]==0.6.0 because these package versions have conflicting dependencies.
The conflict is caused by:
smartsim[dev,ml,mypy] 0.6.0 depends on typing-extensions>=4.9.0; extra == "mypy"
black 24.1a1 depends on typing-extensions>=4.0.1; python_version < "3.11"
onnx 1.14.1 depends on typing-extensions>=3.6.2.1
tensorflow 2.13.1 depends on typing-extensions<4.6.0 and >=3.6.6
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the …
```
=> Relax typing extensions required version

pyproject.toml, setup.cfg, smartsim/_core/utils/redis.py, smartsim/database/orchestrator.py, smartsim/entity/dbobject.py, smartsim/entity/ensemble.py, smartsim/entity/model.py, smartsim/ml/data.py, smartsim/ml/tf/data.py
Add and ship `py.typed` marker per [pep-561](https://peps.python.org/pep-0561/). This change will help change the `mypy` output for this script
```py
from smartsim import Experiment
from smartredis import Client
exp = Experiment(b"my-exp")  # Should err expected str
client = Client(False)
reveal_type(exp)
reveal_type(client)
```
from this
```sh
$ mypy script.py
script.py:1: error: Skipping analyzing "smartsim": module is installed, but missing library stubs or py.typed marker  [import-untyped]
script.py:1: note: See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-imports
script.py:2: error: Skipping analyzing "smartredis": module is installed, but missing library stubs or py.typed marker  [import-untyped]
script.py:7: note: Revealed type is "Any"
script.py:8: note: …
```
=> Expose SS Typehints

smartsim/settings/base.py, smartsim/settings/slurmSettings.py, smartsim/wlm/slurm.py, tests/full_wlm/test_slurm_allocation.py, tests/test_slurm_get_alloc.py
This PR merges in functionality to validate the timing format when requesting a slurm allocation. Previously, no check was required leading to the WLM responsibility to throw an error. With the new code, SmartSim will catch and throw.
=> Validate Slurm Timing format

doc/changelog.rst, tests/backends/test_dbmodel.py
When running the SmartSim test suite with the Torch backend installed, warnings are surfaced as shown below:
```
tests/backends/test_dbmodel.py::test_pt_db_model
/Users/torch/jit/_trace.py:1084: TracerWarning: Output nr 1. of the traced function does not match the corresponding output of the Python function. Detailed error:
Tensor-likes are not close!
Mismatched elements: 10 / 10 (100.0%)
Greatest absolute difference: 0.0451509952545166 at index (0, 9) (up to 1e-05 allowed)
Greatest relative difference: 0.019849935548005467 at index (0, 9) (up to 1e-05 allowed)
_check_trace(
```
This appears to stem from not having the ``eval()`` function invoked before jit tracing and saving the model.  It appears after adding this call that warnings no longer appear.
=> Add eval() to remove Torch warnings during testing

smartsim/_core/control/manifest.py, tests/test_manifest.py
Refactor logic of `Manifest.has_db_objects` to remove excess branching and improve readability/maintainability.
=> Manifest: has DB objects refactor

setup.py, smartsim/_core/config/config.py, smartsim/_core/utils/serialize.py, tests/test_config.py
This PR makes several patch changes to prepare for a SmartSim release including:
=> Patch Changes for Release Prep

smartsim/log.py, tests/test_logs.py
The current `log.get_logger()` function has two issues.
1. it uses `_get_log_level()` to access the value of `SMARTSIM_LOG_LEVEL`, and uses its return value to define whether the logger name should just be SmartSim, or the user-provided one. The problem is that the user-provided one is used only when `_get_log_level()` returns `developer`, but that is never the case, as `developer` gets translated to `debug`.
2. As a consequence of 1, calling `get_logger(name="MY_LOGGER", log_level="INFO")` will always get the logger named `SmartSim` and set its level to info. When this is done in a test, then the log level will be set for all subsequent tests, no matter what the name is set to.
I proposed to replace the `_get_log_level()` with `_translate_log_level()` and use the return value to set the …
=> Use developer log level, protect logger defaults in test

smartsim/log.py, tests/test_logs.py
This PR fixes a bug which prevented the expected behavior when the `SMARTSIM_LOG_LEVEL` environment variable was set to `developer`.
[ committed by @al-rigazzi ]
[ reviewed by @MattToast @ankona ]
=> Use developer log level, protect logger defaults in test (#473)

smartsim/entity/ensemble.py, tests/backends/test_dbmodel.py, tests/backends/test_dbscript.py
This PR prevents duplicate ML models and scripts names being added to an Ensemble member if the names exists already.
The checks are performed for `Ensemble.add_ml_model()`, `Ensemble.add_model()`, `Ensemble.add_script()` and `Ensemble.add_function()`.
=> Duplicate DBModel/Script prevention

doc/changelog.rst, doc/installation_instructions/basic.rst
[docs.tgz](https://github.com/CrayLabs/SmartSim/files/14201965/docs.tgz)
Separate instructions are now included for Mac OSX on Apple Silicon. The most important: 
- `core.autoclrf=true` when cloning SmartSim to avoid errors when building due to line-ending conventions during the Redis build
- Only PyTorch is supported for that platform
=> Update instructions for Apple Silicon

smartsim/_core/control/controller.py, tests/test_controller_errors.py, tests/test_experiment.py, tests/test_launch_errors.py
This PR prevents the launch of entities with names that already exist in the Experiment.
=> Duplicate entity name prevention

doc/changelog.rst, smartsim/experiment.py
Currently, the ``start``, ``stop``, ``generate``, and ``get_status`` API functions list ``t.any`` as the type for ``*args``.  However, that is not specifically true, and underlying methods like ``Controller.start()`` specify ``t.Union[SmartSimEntity, EntitySequence[SmartSimEntity]]``.  This PR updates the typing on the ``Experiment`` API functions to reflect internal API requirements.
=> Change generic t.any in Experiment API

.github/workflows/build_docs.yml, doc/changelog.rst
The deploy_dev_docs action was failing due to running out of disk space in the container. This was alleviated by running the `maximize-build-space` Github action.
=> Increase disk space in container for doc builder

.github/workflows/run_tests.yml, smartsim/_core/_install/buildenv.py, smartsim/_core/utils/redis.py
A fix in the build scripts of redis 7.2.4 modifies build behavior on MacOS on Apple Silicon. The change fixes an issue where incorrect compiler flags are defined and result in build failures due to the `redis_fstat` macro
=> bump redis dep to 7.2.4

.github/workflows/run_tests.yml, doc/changelog.rst, smartsim/_core/_install/buildenv.py, smartsim/_core/utils/redis.py
A fix in the build scripts of Redis 7.2.4 modifies build behavior on MacOS on Apple Silicon. The change fixes an issue where incorrect compiler flags are defined and result in build failures due to the `redis_fstat` macro
=> Update Redis dependency to 7.2.4

doc/changelog.rst, pyproject.toml, smartsim/_core/_cli/build.py, smartsim/_core/generation/modelwriter.py, smartsim/database/orchestrator.py, smartsim/entity/ensemble.py, smartsim/entity/model.py
Configure mypy to raise an error when:
- An instance of an object is used for a boolean check when neither `__bool__` or `__len__` are implemented
- A `Iterator` is used on a boolean check when the author almost certainly wanted a `Collection`
Fixes up/refactors areas of the code base where these potential errors linger.
=> Mypy: Error on Common Truthy Mistakes

doc/api/smartsim_api.rst, doc/changelog.rst, smartsim/settings/base.py, smartsim/settings/slurmSettings.py, tests/test_run_settings.py, tests/test_slurm_settings.py
This PR adds the method `set_node_feature` to srunSettings that accepts a str or list of strs. Users may now specify node constraints for slurm jobs.
=> Specify node feature for slurm job

conftest.py, doc/changelog.rst, smartsim/_core/control/controller.py, smartsim/_core/control/jobmanager.py, smartsim/_core/utils/helpers.py, tests/test_helpers.py, tests/test_interrupt.py
Fixes unfalsifiable test that tests SmartSim's custom SIGINT signal handler. Adds infrastructure to make the test pass again.
=> Enhanced Signal Management

doc/changelog.rst, setup.py, smartsim/_core/utils/telemetry/telemetry.py
Updated watchdog dependency pin to next major version and removed `type: ignore` where possible due to new type hints added to watchdog
=> Update watchdog dependency

smartsim/_core/entrypoints/dragon.py, smartsim/_core/launcher/dragon/dragonBackend.py, smartsim/_core/launcher/dragon/dragonLauncher.py, smartsim/_core/launcher/dragon/dragonSockets.py, smartsim/_core/utils/security.py, tests/test_dragon_launcher.py, tests/utils/test_security.py
1. ZMQ authenticators appear to have clashing inproc addresses when using the `zmq.Context.instance()` factory method. Replaced as needed.
2. Updated underlying `Dragon` library version, which included a breaking changing causing the swap from `TemplateProcess` to `ProcessTemplate`
3. Fixed incomplete permission set on curve key files
=> Decouple authenticator and socket creation

smartsim/_core/control/job.py, smartsim/_core/entrypoints/telemetrymonitor.py, smartsim/_core/utils/telemetry/manifest.py, smartsim/_core/utils/telemetry/telemetry.py, tests/test_telemetry_monitor.py
Pre-dragon launchers used the task/step name to retrieve updates while the dragon launcher uses the `task_id`. This fix ensures that the name for dragon tasks is mapped appropriately.
=> Fix name mapping for dragon steps

doc/changelog.rst, smartsim/_core/control/controller.py, tests/test_telemetry_monitor.py
Reorder experiment startup to ensure telemetry monitor registers event listeners prior to launching entities.
=> Fix telemetry monitor listener registration timeline

doc/changelog.rst, smartsim/_core/utils/telemetry/telemetry.py
Ensures that a managed step-mapping doesn't include a `task_id`.
The telemetry monitor exhibits a defect where it logs errors from a task manager, even with only managed tasks being monitored for updates:
This fix modifies the telemetry monitor to not set a `task_id` when adding items to the `step_mapping` collection. This avoids triggering lookups for unmanaged processes.
=> Avoid setting `task_id` on a managed step in telemetry monitor

.gitignore, doc/changelog.rst, tests/on_wlm/test_het_job.py, tests/test_launch_errors.py, tests/test_model.py
In this PR I removed the defensive regexp in `.gitignore` and added `test_dir` to the tests that were writing to the `cwd` instead of the `test_output` directory.
=> Remove defensive regexp in .gitignore

doc/changelog.rst, tests/backends/test_onnx.py, tests/full_wlm/test_generic_orc_launch_batch.py, tests/on_wlm/test_het_job.py
Fixes:
- `tests/backends/test_onnx.py::test_sklearn_onnx`
- Correctly set number of tasks when not using the local launcher
- Makes sure the DB is not left running on test failure
- `tests/full_wlm/test_generic_orc_launch_batch.py::test_launch_cluster_orc_reconnect`
- Look for pickle file under the orchestrator path rather than the test dir
- Makes sure that DB is cleaned up correctly on test failure
Quiets:
- `tests/on_wlm/test_het_job.py`
- All experiments under the test module are given an explict test path
=> Fix failing and noisy WLM test

doc/changelog.rst, smartsim/_core/utils/serialize.py
The `manifest.json` version needs to be bumped from `0.0.3` to `0.0.4` to match the version of SmartDashboard.
=> Bump manifest.json version to 0.0.4

smartsim/_core/control/previewrenderer.py, smartsim/templates/templates/preview/plain_text/base.template, smartsim/templates/templates/preview/plain_text/clientconfig.template, smartsim/templates/templates/preview/plain_text/clientconfigcolo.template, smartsim/templates/templates/preview/plain_text/ensemble.template, smartsim/templates/templates/preview/plain_text/ensemble_debug.template, smartsim/templates/templates/preview/plain_text/ensemble_info.template, smartsim/templates/templates/preview/plain_text/model.template, smartsim/templates/templates/preview/plain_text/orchestrator.template
Avoid detailed paths in templates by configuring the template loader to use output format
=> Use relative paths with specific loader config

doc/changelog.md, doc/installation_instructions/platform/olcf-summit.rst, doc/tutorials/ml_training/surrogate/train_surrogate.ipynb, pyproject.toml, setup.cfg, setup.py, smartsim/_core/_install/buildenv.py, tests/install/test_buildenv.py
Fixes a build error encountered after the latest update of `setuptools`.
- Fixed non-working links causing documentation build to fail validation
=> Fix build error caused by use of deprecated pkg_resources

doc/changelog.md, docker/prod-cuda11/Dockerfile, docker/prod-cuda12/Dockerfile
The existing dockerfiles did not have the necessary environments to enable GPU support for users wanting to run the tutorials. Two Dockerfiles (for CUDA 11.8 and 12.1) are provided. Note that this has only been tested on a workstation and no HPC support should be expected at this time.
=> Add Dockerfiles with CUDA support

doc/changelog.md, tests/test_manifest.py
Fix unit tests that omit an experiment path and write to the root directory of the project.
- Added typehints to enable successfully passing `mypy test_manifest.py`
- Refactored test using global variables in pytest parameterization to use a fixture
=> Fix util-tests outputs appearing in root directory

doc/changelog.md, smartsim/_core/mli/infrastructure/control/workermanager.py, smartsim/_core/mli/infrastructure/worker/worker.py, smartsim/_core/mli/message_handler.py, smartsim/_core/mli/mli_schemas/request/request.capnp, smartsim/_core/mli/mli_schemas/request/request_capnp.pyi, tests/mli/test_integrated_torch_worker.py, tests/mli/test_worker_manager.py, tests/test_message_handler/test_request.py
This PR removes `device` from the schemas, MessageHandler, and tests.
=> Remove device attribute from schemas

doc/changelog.md, setup.py
The new major version release of Numpy is incompatible with modules compiled against Numpy 1.x. For both SmartSim and SmartRedis we request a 1.x version of numpy. This is needed in SmartSim because some of the downstream dependencies request NumPy.
=> Restrict to numpy 1.x

doc/changelog.md, smartsim/database/orchestrator.py
This PR will remove a broken link to oss.redis.com that is breaking the documentation build
=> Remove broken redis documentation links

doc/changelog.md, doc/dragon.rst, doc/tutorials/online_analysis/lattice/online_analysis.ipynb, smartsim/_core/launcher/dragon/dragonBackend.py, smartsim/_core/launcher/dragon/dragonLauncher.py, smartsim/_core/launcher/step/dragonStep.py, smartsim/_core/launcher/step/step.py, smartsim/_core/mli/infrastructure/control/workermanager.py, smartsim/_core/schemas/dragonRequests.py, smartsim/settings/dragonRunSettings.py, tests/test_dragon_client.py, tests/test_dragon_launcher.py, tests/test_dragon_run_policy.py, tests/test_dragon_run_request.py, tests/test_dragon_run_request_nowlm.py, tests/test_dragon_runsettings.py, tests/test_dragon_step.py
Adds the ability to specify hardware affinities for cpu/gpu devices. Creates a dragon policy that uses provided policy to modify the resulting dragon `ProcessGroup`.
=> Add ability to specify hardware policies on dragon run requests

doc/changelog.md, smartsim/_core/launcher/dragon/dragonBackend.py
This PR addresses an inconstent internal host name representation in the Dragon backend.
=> Fix-hostname

tests/test_file_operations.py
Running `pytest tests/test_file_operations.py` was overwriting a test configuration file. This PR fixes the offending test and adds a missing `assert` statement.
=> Fix test overwriting a test configuration file

.github/workflows/run_tests.yml, doc/changelog.md, smartsim/_core/_cli/scripts/dragon_install.py
This PR mitigates two issues encountered during installation on build agents
Installation of mypy or dragon in separate build actions caused some dependencies (typing_extensions, numpy) to be upgraded. Those upgrades result in runtime failures. The build actions were tweaked to allow pip to consider all optional dependencies during resolution. 
Additionally, the numpy version was capped on dragon installations.
=> Mitigate dragon/numpy, mypy/typing_extension dependency issues

.github/workflows/run_tests.yml, doc/changelog.md, smartsim/_core/_cli/scripts/dragon_install.py, tests/test_dragon_installer.py
Fix two dragon installation issues:
1. Fix issue where search for `*.whl` files may include previously extracted versions of the dragon package
2. Fix issue where LD_LIBRARY_PATH is incorrectly directed to `dragon-0.9` folder by using the generated `.env` file created from `smart build --dragon`
=> Fix dragon installation issues

doc/changelog.md, setup.py
The builder module was included in `setup.py` to allow us to ship the main Redis binaries (not RedisAI) with installs from PyPI. The changes in this PR remove our ability to do this and requires users to build Redis as part of the `smart build`. This change in behaviour is justified by the following:
- The additional cost/complexity to the user for building Redis is minimal due to the pre-existing need to compile RedisAI.
- Removes the need for different platform-dependent wheels
- Frees the builder module from being a single file to allow convenient import into `setup.py`.
=> Remove builder from setup.py

doc/changelog.md, ex/high_throughput_inference/mock_app.py, smartsim/_core/mli/infrastructure/worker/torch_worker.py
During memory profiling we found that `torch.tensor` makes a copy and `torch.from_numpy` does not. We only use `torch.tensor` in `torch_worker.py`, so this is a very small change.
I also added in a change to `mock_app.py` after some discussion that we may not want to return tensors, but we can have more discussion surrounding this if necessary.
=> Use `torch.from_numpy` instead of `torch.tensor` to reduce a copy

smartsim/_core/control/jobmanager.py, smartsim/_core/control/launch_history.py, smartsim/_core/launcher/dragon/dragonBackend.py, smartsim/_core/launcher/dragon/dragonLauncher.py, smartsim/_core/utils/helpers.py, smartsim/error/errors.py, smartsim/experiment.py, smartsim/settings/dispatch.py, smartsim/status.py, tests/temp_tests/test_settings/conftest.py, tests/temp_tests/test_settings/test_dispatch.py, tests/test_experiment.py, tests/test_launch_history.py
Add ability for the `Experiment` to fetch the status a launched job that it started given a `LaunchedJobID`. Teach the `ShellLauncher` and `DragonLauncher` to get statuses of jobs they have launched.
=> Simple Status Checking

doc/changelog.md, ex/high_throughput_inference/mock_app.py, ex/high_throughput_inference/standalone_workermanager.py, smartsim/_core/launcher/dragon/dragonBackend.py, smartsim/_core/mli/infrastructure/environmentloader.py, tests/dragon/test_environment_loader.py, tests/dragon/test_error_handling.py, tests/dragon/test_worker_manager.py
`SS_INFRA_BACKBONE` has been updated to `_SMARTSIM_INFRA_BACKBONE` and `SS_REQUEST_QUEUE` is now `_SMARTSIM_REQUEST_QUEUE`.
=> MLI environment variables updated using new naming convention

doc/changelog.md, smartsim/_core/mli/infrastructure/storage/featurestore.py, tests/mli/test_core_machine_learning_worker.py
We only used pydantic BaseModels in `FeatureStoreKey`, so I converted that into a dataclass and used `_post_init_` to validate that the key and descriptor are not empty strings. I also made the dataclass frozen.
=> Remove pydantic dependency from MLI code

smartsim/_core/launcher/dragon/dragonBackend.py, smartsim/_core/launcher/dragon/pqueue.py, tests/test_dragon_run_request.py, tests/test_node_prioritizer.py
Fix 3 bugs:
1. reordering the init sequence in the dragon backend resulted in an un-set collection being used
2. fix tests that should have been updated to compare set contents instead of individual items
3. remove newly added validation on empty host lists that broke existing tests
=> fix init reordering bug

doc/changelog.md, smartsim/_core/mli/infrastructure/control/error_handling.py, tests/dragon/test_error_handling.py
In this PR I fix the `exception_handler` so that it only builds and serializes a failure response if a reply channel is not None. I also needed to tweak the tests a bit by mocking out the reply channels.
=> Refactor `exception_handler` to avoid unnecessary building and serialization of failure responses.

doc/changelog.md, smartsim/_core/_cli/build.py, smartsim/_core/_install/builder.py, smartsim/_core/config/config.py, smartsim/_core/utils/helpers.py, smartsim/database/orchestrator.py, smartsim/experiment.py, tests/on_wlm/test_dragon.py, tests/test_config.py
This PR updates environment variable names with the new convention. 
`SMARTSIM_DRAGON_SERVER_PATH_EXP` -> `_SMARTSIM_DRAGON_SERVER_PATH_EXP` 
`RAI_PATH` -> `SMARTSIM_RAI_LIB`
`REDIS_PATH` -> `SMARTSIM_REDIS_SERVER_EXE`
`REDIS_CLI_PATH` -> `SMARTSIM_REDIS_CLI_EXE`
`REDIS_CONF` -> `SMARTSIM_REDIS_CONF`
=> SmartSim environment variables updated using new naming convention

smartsim/_core/control/job.py, smartsim/_core/dispatch.py, smartsim/_core/launcher/dragon/dragonLauncher.py, smartsim/_core/shell/shellLauncher.py, smartsim/_core/utils/launcher.py, smartsim/entity/application.py, smartsim/entity/entity.py, smartsim/entity/entityList.py, smartsim/experiment.py, smartsim/settings/arguments/launch/lsf.py, smartsim/settings/arguments/launch/slurm.py, tests/temp_tests/test_launchable.py, tests/temp_tests/test_settings/conftest.py, tests/temp_tests/test_settings/test_alpsLauncher.py, tests/temp_tests/test_settings/test_dragonLauncher.py, tests/temp_tests/test_settings/test_localLauncher.py, tests/temp_tests/test_settings/test_lsfLauncher.py, tests/temp_tests/test_settings/test_mpiLauncher.py, tests/temp_tests/test_settings/test_palsLauncher.py, tests/temp_tests/test_settings/test_slurmLauncher.py, tests/test_experiment.py, tests/test_shell_launcher.py
Refactor SmartSimEntity class, remove ExecutableProtocol protocol, Application becomes subclass of ABC SmartSImEntity
=> Refine SmartSimEntity Interface

doc/changelog.md, setup.py
The release of watchdog v5 introduced new types which caused further errors with mypy. To mitigate these errors for now, we pin the watchdog version to 4.x and will resolve these errors in the future.
=> Pin watchdog version to prevent mypy errors

smartsim/_core/shell/shellLauncher.py
In the shell launcher, an unintended and unused type union sunk into the ``ShellLauncherCommand`` type for the ``command_tuple`` type, allowing the attr to be of type ``Sequence[str]`` or ``tuple[str, tuple[str, ...]]``. The former works as expected, but the latter would error at runtime when sent to the ``ShellLauncher`` when opening a subprocess.
```py
class ShellLauncher:
...
def start(self, shell_command: ShellLauncherCommand) -> LaunchedJobID:
...
exe, *rest = shell_command.command_tuple
expanded_exe = helpers.expand_exe_path(exe)
self._launched[id_] = sp.Popen(
(expanded_exe, *rest),
cwd=shell_command.path,
env={k: v for k, v in shell_command.env.items() if v is not None},
stdout=shell_command.stdout,
stderr=shell_command.stderr,
)
...
```
Because this type was not being used, it …
=> Remove Problematic Type Union

.github/workflows/run_tests.yml, doc/changelog.md, doc/installation_instructions/basic.rst, smartsim/_core/_cli/build.py, smartsim/_core/_cli/scripts/dragon_install.py, smartsim/_core/_install/builder.py, smartsim/_core/config/config.py, tests/dragon/channel.py, tests/dragon/test_featurestore_base.py, tests/test_dragon_installer.py, tests/test_dragon_launcher.py
Parameterize the `smart build --dragon` command to enable specification of a fork/repository and package version
- add parameter `--dragon-repo`
- add parameter `--dragon-version`
Sample usage:
- Get latest version from private fork
`GH_TOKEN=xxxxx smart build --dragon-repo ankona/dragonfork`
- Get specific version from private fork
`GH_TOKEN=xxxxx smart build --dragon-repo ankona/dragonfork --dragon-version 0.10`
- Get specific version from public fork
- `GH_TOKEN=xxxxx smart build --dragon-repo dragonhpc/dragon --dragon-version 0.10`
- `GH_TOKEN=xxxxx smart build --dragon-version 0.10`
- `smart build --dragon-repo dragonhpc/dragon --dragon-version 0.10`
- `smart build --dragon-version 0.10`
1. OK - `smart build --dragon`
```
[1] % smart build --dragon
[SmartSim] INFO Running SmartSim …
```
=> Parametrize dragon install

doc/changelog.md, doc/installation_instructions/platform/frontier.rst, doc/installation_instructions/platform/perlmutter.rst
After discussing with admins at OLCF, miniforge is the preferred solution for creating virtual environments on Frontier. The instructions for installing SmartSim have been updated accordingly. Additionally, perlmutter did not have a step for compiling the SmartRedis libraries. This has been rectified to bring the two systems to parity.
=> Refine install documentation for Perlmutter and Frontier

doc/changelog.md, doc/installation_instructions/platform/frontier.rst
On Frontier, the recommended way to activate conda environments is
to go through source activate. This also means that ``conda init``
is not needed. The instructions for Frontier have been updated to 
reflect this.
=> Change 'conda activate' to 'source activate' for Frontier

doc/changelog.md, doc/installation_instructions/platform/frontier.rst
Based on feedback from OLCF, users may need to se the MIOPEN cache prior to running `smart validate`. The installation instructions for Frontier have been updated accordingly.
=> Make a user-specific db cache

.github/workflows/release.yml, doc/changelog.md
Removes the use of CI Build Wheel now that SmartSim is a pure python package.
=> Update release action to remove CI Build Wheel
