- .github/workflows/release.yml
As the title states, small change to CD.
> Change CD action to only invoke on publish

- smartsim/_core/launcher/step/slurmStep.py
Amendment to PR https://github.com/CrayLabs/SmartSim/pull/170. 
Missed an instance of moving `SrunSettings.format_env_vars` to `SrunSettings.format_comma_sep_env_vars` in `SrunStep`
> Change Env Format Method

- smartsim/_core/_install/builder.py
Add validation of redis-server and redis-cli installation, based on how we'll expect to find them in config, to builder class
> Validate redis-server/redis-cli install

- doc/changelog.rst
New release notes, which are those written by Andrew, with just a few reworded sentences.
> Release notes 0.4.1

- Makefile
- README.md
- doc/_static/version_names.json
- doc/conf.py
- doc/experiment.rst
- doc/installation.rst
- docker-compose.yml
- docker/dev/Dockerfile
- docker/prod/Dockerfile
- requirements-dev.txt
- requirements.txt
- smartsim/_core/_install/buildenv.py
- tests/on_wlm/test_wlm_orc_config_settings.py
- tests/test_orc_config_settings.py
Update default versions of SmartSim and SmartRedis for installation
> Update default versions

- README.md
This PR updates the citation on `README.md`
> New citation

- doc/index.rst
- doc/sr_dataset_conversions.rst
Link the SmartSim to the SmartRedis dataset conversion documentation.
> Link documentation to SmartRedis for dataset conversion 

- conftest.py
- doc/changelog.rst
- smartsim/_core/_install/buildenv.py
- tests/test_orc_config_settings.py
Update Redis from 6.0.8 to 7.0.5
> Update redis version

- .wci.yml
This PR adds the ``.wci.yml`` file that is required for detailed descriptions on the WCI website.  After this PR is merged, a PR will be submitted to WCI repo to add SmartSim.  The description of the ``.wci.yml`` file is given here:
https://workflows.community/systems/contribute
> Addition of .wci.yml for the Workflows Community Initiative website

- README.md
rollback tutorial version numbers until properly published
> Tutorial Version Rollback

- doc/testing.rst
Simplified testing instructions based on the new SmartRedis build and test system
> Update description of testing for SmartRedis

- .wci.yml
- doc/_static/version_names.json
- doc/experiment.rst
- doc/installation_instructions/platform/olcf-summit.rst
- docker/dev/Dockerfile
- docker/prod/Dockerfile
- smartsim/_core/_install/buildenv.py
Bumps relevant version numbers in anticipation of release
> Update SmartSim version numbers

- doc/changelog.rst
Update changelog for PRs previously merged (334, 338, 341)
> Add missing changelog entries

- .wci.yml
- doc/conf.py
- doc/installation_instructions/platform/olcf-summit.rst
- docker/dev/Dockerfile
- docker/prod/Dockerfile
- smartsim/_core/_install/buildenv.py
Update SR dep to 0.4.2, SS version to 0.5.1. This PR should be merged AFTER https://github.com/CrayLabs/SmartRedis/pull/399 in order to pass the CI
> Version Bump

- README.md
- doc/conf.py
- doc/requirements-doc.txt
This PR adds our public email address to the README.md file. The `Slack invite` link has been renamed `Join us on Slack!`.
> Add contact information to README.md

- smartsim/_core/utils/serialize.py
Bump manifest version number to match SmartSim Dashboard
> Manifest Version Bump

- .wci.yml
- Makefile
- doc/_static/version_names.json
- doc/changelog.rst
- doc/conf.py
- doc/installation_instructions/basic.rst
- doc/installation_instructions/platform/olcf-summit.rst
- docker/dev/Dockerfile
- docker/prod/Dockerfile
- smartsim/_core/_install/buildenv.py
Bump up release number.
Also suppress docs warnings.
Wait for SmartRedis v0.5.0 to be released before merging this PR!
> Release 0.6.0

- doc/changelog.rst
This PR updates the changelog to prepare for release.
> Update to changelog for release

- .wci.yml
- Makefile
- doc/_static/version_names.json
- doc/changelog.rst
- doc/conf.py
- doc/installation_instructions/platform/olcf-summit.rst
- docker/prod/Dockerfile
- smartsim/_core/_install/buildenv.py
A critical performance concern was identified and addressed in SmartRedis. A patch fix was deployed, and SmartSim was updated to ensure users do not inadvertently pull the unpatched version of SmartRedis.
> Hot Fix: bump dependency version

- doc/changelog.md
- smartsim/_core/_install/builder.py
Add 'f' to intended f-strings for better error messages
> Add 'f' to f-strs

- doc/changelog.md
- smartsim/_core/entrypoints/service.py
- smartsim/_core/mli/comm/channel/channel.py
- smartsim/_core/mli/comm/channel/dragonchannel.py
- smartsim/_core/mli/infrastructure/control/workermanager.py
- smartsim/_core/mli/infrastructure/storage/dragonfeaturestore.py
- smartsim/_core/mli/infrastructure/storage/featurestore.py
- smartsim/_core/mli/infrastructure/worker/worker.py
- tests/mli/channel.py
- tests/mli/featurestore.py
- tests/mli/test_core_machine_learning_worker.py
- tests/mli/test_default_torch_worker.py
- tests/mli/test_integrated_torch_worker.py
- tests/mli/test_service.py
- tests/mli/test_worker_manager.py
- tests/mli/worker.py
This PR contains an ML worker manager MVP. The worker manager executes a single-threaded version of the planned ML pipeline for a single worker instance.
> ML Worker Manager MVP

- doc/changelog.md
- doc/dragon.rst
- doc/tutorials/online_analysis/lattice/online_analysis.ipynb
- smartsim/_core/launcher/dragon/dragonBackend.py
- smartsim/_core/launcher/dragon/dragonLauncher.py
- smartsim/_core/launcher/step/dragonStep.py
- smartsim/_core/launcher/step/step.py
- smartsim/_core/schemas/dragonRequests.py
- smartsim/settings/dragonRunSettings.py
- tests/test_dragon_client.py
- tests/test_dragon_launcher.py
- tests/test_dragon_run_policy.py
- tests/test_dragon_run_request.py
- tests/test_dragon_run_request_nowlm.py
- tests/test_dragon_runsettings.py
- tests/test_dragon_step.py
> Merge latest develop into mli-feature

- .github/workflows/run_tests.yml
- tests/temp_tests/test_colocatedJobGroup.py
- tests/temp_tests/test_core/test_commands/test_command.py
- tests/temp_tests/test_core/test_commands/test_commandList.py
- tests/temp_tests/test_core/test_commands/test_launchCommands.py
- tests/temp_tests/test_jobGroup.py
- tests/temp_tests/test_launchable.py
- tests/temp_tests/test_settings/test_alpsLauncher.py
- tests/temp_tests/test_settings/test_batchSettings.py
- tests/temp_tests/test_settings/test_common.py
- tests/temp_tests/test_settings/test_dragonLauncher.py
- tests/temp_tests/test_settings/test_launchSettings.py
- tests/temp_tests/test_settings/test_localLauncher.py
- tests/temp_tests/test_settings/test_lsfLauncher.py
- tests/temp_tests/test_settings/test_lsfScheduler.py
- tests/temp_tests/test_settings/test_mpiLauncher.py
- tests/temp_tests/test_settings/test_palsLauncher.py
- tests/temp_tests/test_settings/test_pbsScheduler.py
- tests/temp_tests/test_settings/test_slurmLauncher.py
- tests/temp_tests/test_settings/test_slurmScheduler.py
Add headers/marks/boilerplate to test files for `smartsim-refactor`
> Link up SmartSim Refactor CI

- .github/workflows/run_tests.yml
- doc/changelog.md
This PR updates codecov to version 4.5.0
> Update codecov to 4.5.0
